// export const NOW_PLAYING_HELP_PREFIX = "nowplaying-help";

// export const NOW_PLAYING_HELP_TEXTS: Record<string, string> = {
//   "edit-menu": [
//     "## Manage Now Playing - Help",
//     "Use this menu to manage your Now Playing list from the list header button.",
//     "",
//     "- **Sort** - Rearrange the order your games appear.",
//     "- **Edit Platform** - Set or change which platform you are playing each game on.",
//     "- **Add Completion** - Log that you finished or made notable progress on a game.",
//     "  You can choose whether to announce it to the server.",
//     "- Notes are managed through **Game Journal** entries.",
//     "- **Remove Game** - Permanently remove a game from your Now Playing list.",
//   ].join("\n"),
//   "sort": [
//     "## Sort - Help",
//     "Use the dropdowns to pick which game goes in each position, then press **Save**.",
//     "",
//     "- Each dropdown represents one slot in your list.",
//     "- Pick a different game for each position to rearrange the order.",
//     "- **Reset to current order** puts the dropdowns back to how your list is right now.",
//     "- **Cancel** closes this screen without saving any changes.",
//   ].join("\n"),
//   "platform": [
//     "## Edit Platform - Help",
//     "Use the dropdowns to choose which platform you are playing each game on, then press **Save**.",
//     "",
//     "- Each dropdown corresponds to one game in your list.",
//     "- The platform is shown alongside the game title in your public list.",
//     "- **Reset to current platforms** restores all dropdowns to their current saved values.",
//     "- **Cancel** closes this screen without saving any changes.",
//   ].join("\n"),
//   "remove": [
//     "## Remove Game - Help",
//     "Select a game from the dropdown to remove it from your Now Playing list.",
//     "",
//     "- You can remove multiple games in one session - just select each one in turn.",
//     "- Removing a game also removes its note. Journal entries are kept separately.",
//     "- Press **Done** when you are finished removing games.",
//   ].join("\n"),
//   "journal-optin": [
//     "## Journal Opt-In - Help",
//     "Select a game to switch it from note mode to journal mode.",
//     "",
//     "- **Journal mode** lets you write longer, dated entries about your playthrough",
//     "  instead of a single short note.",
//     "- The journal can be viewed by other members (public entries only).",
//     "- Switching a game to journal mode replaces its note display in your public list.",
//     "- You can only have journal mode enabled on one game at a time per this menu.",
//   ].join("\n"),
//   "completion-pick": [
//     "## Add Completion - Help",
//     "Click **Add Completion** next to the game you want to log a completion for.",
//     "",
//     "- A completion records that you finished or made significant progress on a game.",
//     "- After picking a game you will configure the details on the next screen.",
//     "- Press **Done** if you do not want to log a completion after all.",
//   ].join("\n"),
//   "completion-config": [
//     "## Add Completion Config - Help",
//     "Configure the details for your completion, then press **Continue**.",
//     "",
//     "- **Completion Type** - Choose the kind of completion (e.g. Beaten, 100%, Dropped).",
//     "- **Remove from Now Playing** - Choose Yes to take the game off your active list.",
//     "- **Announce Completion** - Choose Yes to post a message to the server about it.",
//     "- **Add a Completion Note** - Choose Yes to write a short note about the completion.",
//     "- Press **Continue** to open the details form.",
//     "- Press **Cancel** to abort without saving anything.",
//   ].join("\n"),
//   "journal-view": [
//     "## Game Journal - Help",
//     "This is the journal for one game in your Now Playing list.",
//     "",
//     "- **Add Entry** - Write a new journal entry. You can set it as public or private.",
//     "- **Edit Entry** - Update an existing entry's title, body, or privacy setting.",
//     "- **Delete Entry** - Permanently remove an entry.",
//     "- **Prev / Next** - Navigate between pages of entries (5 entries per page).",
//     "",
//     "Public entries are visible to other members when they view your profile.",
//     "Private entries are only visible to you.",
//   ].join("\n"),
//   "journal-edit": [
//     "## Edit Journal Entry - Help",
//     "Select the entry you want to edit from the dropdown.",
//     "",
//     "- After selecting an entry a form will open where you can update",
//     "  the title, body text, and privacy setting.",
//     "- Changes are saved when you submit the form.",
//   ].join("\n"),
//   "journal-delete": [
//     "## Delete Journal Entry - Help",
//     "Select the entry you want to delete from the dropdown.",
//     "",
//     "- You will be asked to confirm before anything is permanently removed.",
//     "- Deleted entries cannot be recovered.",
//   ].join("\n"),
//   "journal-delete-confirm": [
//     "## Confirm Delete - Help",
//     "You are about to permanently delete a journal entry.",
//     "",
//     "- Press **Delete** to confirm and remove the entry for good.",
//     "- Press **Cancel** to go back without deleting anything.",
//   ].join("\n"),
// };
