DECLARE
  v_exists NUMBER;
BEGIN
  SELECT COUNT(*) INTO v_exists
  FROM USER_TABLES
  WHERE TABLE_NAME = 'JOURNAL_MESSAGE_CONTEXTS';

  IF v_exists = 0 THEN
    EXECUTE IMMEDIATE '
      CREATE TABLE JOURNAL_MESSAGE_CONTEXTS (
        CHANNEL_ID     VARCHAR2(30)  NOT NULL,
        MESSAGE_ID     VARCHAR2(30)  NOT NULL,
        CREATED_AT_MS  NUMBER        NOT NULL,
        OWNER_USER_ID  VARCHAR2(30)  NOT NULL,
        GAME_ID        NUMBER        NOT NULL,
        CONSTRAINT PK_JMC PRIMARY KEY (CHANNEL_ID, MESSAGE_ID)
      )';
  END IF;
END;
/
